package com.timetrade.lamdatest;

import java.util.Map;
import com.amazonaws.services.lambda.runtime.Context; 
import com.amazonaws.services.lambda.runtime.RequestHandler;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App implements RequestHandler<MapType, Integer>{

	public Integer handleRequest(MapType input, Context context){
		int countA = input.getValA();
		int countB = input.getValB();
		return new Integer(countA+countB);
	}

	public App(){}

	public static void main(String args[]){

	}	

}
